export const GET_TASKS_API = "GET_TASKS_API";
export const GET_TASKS_API_LOAD = "GET_TASKS_API_LOAD";
export const GET_TASKS_API_SUCCESS = "GET_TASKS_API_SUCCESS";
export const GET_TASKS_API_FAILURE = "GET_TASKS_API_FAILURE";
export const POST_NEW_TASK = "POST_NEW_TASK";
export const POST_UPDATED_TASK = "POST_UPDATED_TASK";
export const POST_UPDATED_STORE = "POST_UPDATED_STORE";
export const POST_TASK_FAILURE = "POST_TASK_FAILURE";
export const DELETE_TASK = "DELETE_TASK";
export const DELETE_TASK_FAILURE = "DELETE_TASK_FAILURE";

export const CLOSE_MODAL = "CLOSE_MODAL";
export const SHOW_MODAL = "SHOW_MODAL";

export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_LOAD = "LOGIN_USER_LOAD";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_FAILURE = "LOGIN_USER_FAILURE";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER = "REGISTER";
export const REGISTER_USER_LOAD = "REGISTER_USER_LOAD";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILURE = "REGISTER_FAILURE";

export const GET_SETTINGS = "GET_SETTINGS";
export const GET_SETTINGS_SUCCESS = "GET_SETTINGS_SUCCESS";
export const GET_SETTINGS_FAILURE = "GET_SUCCESS_FAILURE";
export const UPDATE_SETTINGS = "UPDATE_SETTINGS";
export const UPDATE_SETTINGS_SUCCESS = "UPDATE_SETTINGS_SUCCESS";
export const UPDATE_SETTINGS_FAILURE = "UPDATE_SETTINGS_FAILURE";
export const POST_DEFAULT_SETTINGS = "POST_DEFAULT_SETTINGS";
export const POST_DEFAULT_SETTINGS_FAILURE = "POST_DEFAULT_SETTINGS_FAILURE";
